Configurado para GHA

diff --git a/.github/workflows/R-CMD-check.yaml b/.github/workflows/R-CMD-check.yaml
--- a/.github/workflows/R-CMD-check.yaml
+++ b/.github/workflows/R-CMD-check.yaml
@@ -1,9 +1,10 @@
+# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
+# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
 on:
-  # Cria um botão para disparar o job
   workflow_dispatch:
-    branches: [main]
+    branches: [main, master]
 
-name: rodar-gpt3
+name: run-r-script
 
 jobs:
   run-r-script:
@@ -11,13 +12,11 @@ jobs:
     env:
       GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
       OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
-
     steps:
       - uses: actions/checkout@v3
       - uses: r-lib/actions/setup-r@v2
         with:
-          use-public-rspm: true # Para usar binários no Linux (mais rápido)
-
+          use-public-rspm: true
       - uses: r-lib/actions/setup-r-dependencies@v2
         with:
           cache-version: 2
@@ -27,10 +26,10 @@ jobs:
       - name: run-script
         run: Rscript inst/rodar-gpt3.R
 
-      - name: baixar-para-github
+      - name: commit files
         run: |
           git config --local user.name "$GITHUB_ACTOR"
           git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
           git add -A
-          git commit -m "Atualiza arquivos - por 04-run-r-script" || echo "no changes to commit"
+          git commit -m "Atualiza arquivos - por 04-r-script" || echo "no changes to commit"
           git push origin || echo "no changes to commit"
